const data = [
    {
        level: 1,
        title: 'Type Selector',
        subtitle: 'Select elements by their type',
        symbol: 'A',
        description: 'Selects all elements of type <span class="information__tag">A</span>. Type refers to the type of tag, so <span class="information__tag">&lt;div&gt;</span>, <span class="information__tag">&lt;p&gt;</span> are all different element types.',
        tag: '<span class="information__tag">&lt;p&gt;</span> selects all <span class="information__tag">&lt;p&gt;</span> elements.',
    },
    {
        level: 2,
        title: 'Type Selector',
        subtitle: 'Select elements by their type',
        symbol: 'A',
        description: 'Selects all elements of type <span class="information__tag">A</span>. Type refers to the type of tag, so <span class="information__tag">&lt;div&gt;</span>, <span class="information__tag">&lt;p&gt;</span> are all different element types.',
        tag: '<span class="information__tag">&lt;p&gt;</span> selects all <span class="information__tag">&lt;p&gt;</span> elements.',
    },
    {
        level: 3,
        title: 'ID Selector',
        subtitle: 'Select elements with an ID',
        symbol: '#id',
        description: 'Selects the element with a specific <span class="information__tag">id</span>. You can also combine the ID selector with the type selector.',
        tag: '<span class="information__tag">#cool</span> selects any element with <span class="information__tag">id="cool"</span>',
    },
    {
        level: 4,
        title: 'Descendant Selector',
        subtitle: 'Select an element inside another element',
        symbol: 'A  B',
        description: 'Selects all <span class="information__tag">B</span> inside of <span class="information__tag">A</span>. <span class="information__tag">B</span> is called a descendant because it is inside of another element.',
        tag: '<span class="information__tag">p  strong</span> selects all <span class="information__tag">&lt;strong&gt;</span> elements that are inside of any <span class="information__tag">&lt;p&gt;</span>',
    },
    {
        level: 5,
        title: 'Combine the Descendant & ID Selectors',
        subtitle: '',
        symbol: '#id  A',
        description: 'You can combine any selector with the descendent selector.',
        tag: '<span class="information__tag">#cool span</span> selects all <span class="information__tag">&lt;span&gt;</span> elements that are inside of elements with <span class="information__tag">id="cool"</span>',
    },
    {
        level: 6,
        title: 'Class Selectors',
        subtitle: 'Select elements by their class',
        symbol: '.classname',
        description: 'The class selector selects all elements with that class attribute. Elements can only have one ID, but many classes.',
        tag: '<span class="information__tag">.neato</span> selects all elements with <span class="information__tag">class="neato"</span>',
    },
    {
        level: 7,
        title: 'Combine the Class Selector',
        subtitle: '',
        symbol: 'A.className',
        description: 'You can combine the class selector with other selectors, like the type selector.',
        tag: '<span class="information__tag">ul.important</span> selects all <span class="information__tag">&lt;ul&gt;</span> elements that have <span class="information__tag">class="important"</span>',
    },
    {
        level: 8,
        title: 'You can do it...',
        subtitle: '',
        symbol: 'Put your back into it!',
        description: 'Combine what you learned in the last few levels to solve this one!',
        tag: '',
    },
    {
        level: 9,
        title: 'Comma Combinator',
        subtitle: 'Combine, selectors, with... commas!',
        symbol: 'A, B',
        description: 'Thanks to Shatner technology, this selects all <span class="information__tag">A</span> and <span class="information__tag">B</span> elements. You can combine any selectors this way, and you can specify more than two.',
        tag: '<span class="information__tag">p, .fun</span> selects all <span class="information__tag">&lt;p&gt;</span> elements as well as all elements with <span class="information__tag">class="fun"</span>',
    },
    {
        level: 10,
        title: 'The Universal Selector',
        subtitle: 'You can select everything!',
        symbol: '*',
        description: 'You can select all elements with the universal selector!',
        tag: '<span class="information__tag">p *</span> selects any element inside all <span class="information__tag">&lt;p&gt;</span> elements.',
    },

];

export default data;
